---
- hosts: webserver
  
  tasks:
  - name: Install needed packages to host NGINX Service
    yum: name={{item}} state=installed update_cache=yes
    with_items:
      - nginx
    become: true

  - template: src=nginx.j2 dest=/etc/nginx/nginx.conf
    become: true

  - name: ensure nginx is running
    service: name=nginx state=started
    become: true

  
